# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up JDK 22
      # TODO: Switch back to actions/setup-java@v4 once they support JDK 22 for temurin
      #uses: actions/setup-java@v4 # https://github.com/actions/setup-java
      #with:
      #  java-version: '22'
      #  distribution: 'temurin'
      #  cache: maven
      uses: oracle-actions/setup-java@v1 # https://github.com/oracle-actions/setup-java
      with:
        website: jdk.java.net
        release: 22

    - name: Print Java version
      run: java -version

    - name: Verify and Package with Maven
      run: ./mvnw --batch-mode --file pom.xml verify package

    # Upload the full dependency graph to GitHub to improve the quality of
    # Dependabot alerts this repository can receive.
    - name: Submit Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@v4
